#!/bin/sh
set -e

# python create_segmentation_map.py -f test_040
python create_segmentation_map.py -f test_090
python create_segmentation_map.py -f test_026
python create_segmentation_map.py -f test_104
python create_segmentation_map.py -f test_027
python create_segmentation_map.py -f test_002
python create_segmentation_map.py -f test_029
python create_segmentation_map.py -f test_001
python create_segmentation_map.py -f test_061
python create_segmentation_map.py -f test_108
python create_segmentation_map.py -f test_110
python create_segmentation_map.py -f test_004
python create_segmentation_map.py -f test_092
python create_segmentation_map.py -f test_066
python create_segmentation_map.py -f test_122
python create_segmentation_map.py -f test_074
python create_segmentation_map.py -f test_079
python create_segmentation_map.py -f test_084
python create_segmentation_map.py -f test_117
python create_segmentation_map.py -f test_010
python create_segmentation_map.py -f test_011
python create_segmentation_map.py -f test_102
python create_segmentation_map.py -f test_097
python create_segmentation_map.py -f test_116
python create_segmentation_map.py -f test_016
python create_segmentation_map.py -f test_068
python create_segmentation_map.py -f test_075
python create_segmentation_map.py -f test_113
python create_segmentation_map.py -f test_094
python create_segmentation_map.py -f test_082
python create_segmentation_map.py -f test_105
python create_segmentation_map.py -f test_073
python create_segmentation_map.py -f test_071
python create_segmentation_map.py -f test_121
python create_segmentation_map.py -f test_064
python create_segmentation_map.py -f test_065
python create_segmentation_map.py -f test_069
python create_segmentation_map.py -f test_051
python create_segmentation_map.py -f test_008
python create_segmentation_map.py -f test_033
python create_segmentation_map.py -f test_030
python create_segmentation_map.py -f test_048
python create_segmentation_map.py -f test_052
python create_segmentation_map.py -f test_046
python create_segmentation_map.py -f test_099
python create_segmentation_map.py -f test_038
python create_segmentation_map.py -f test_013
python create_segmentation_map.py -f test_116
